function severityRank(severity) {
  return { critical: 0, high: 1, medium: 2 }[severity] ?? 3;
}

export function buildMarkdownReport(scan) {
  const lines = [];
  const exposedEnv = scan.envFiles.filter((f) => !f.ignored);
  const sortedSecrets = [...scan.secrets].sort((a, b) => severityRank(a.severity) - severityRank(b.severity));

  lines.push("# Security Token Janitor — Scan Report");
  lines.push("");
  lines.push(`- **Scanned path:** \`${scan.root}\``);
  lines.push(`- **Scanned at:** ${new Date(scan.scannedAt).toLocaleString()}`);
  lines.push(`- **.env files found:** ${scan.envFiles.length} (${exposedEnv.length} exposed)`);
  lines.push(`- **Leaked credentials found:** ${scan.secrets.length}`);
  lines.push("");

  lines.push("## .env Files");
  lines.push("");
  if (scan.envFiles.length === 0) {
    lines.push("No `.env` files found.");
  } else {
    lines.push("| File | Status |");
    lines.push("| --- | --- |");
    for (const f of scan.envFiles) {
      lines.push(`| \`${f.file}\` | ${f.ignored ? "Ignored" : "**EXPOSED**"} |`);
    }
  }
  lines.push("");

  lines.push("## Potential Leaked Credentials");
  lines.push("");
  if (sortedSecrets.length === 0) {
    lines.push("No suspicious credentials found.");
  } else {
    lines.push("| Severity | Type | Location | Preview |");
    lines.push("| --- | --- | --- | --- |");
    for (const s of sortedSecrets) {
      const severity = (s.severity ?? "medium").toUpperCase();
      lines.push(`| ${severity} | ${s.type} | \`${s.file}:${s.line}\` | \`${s.preview}\` |`);
    }
  }
  lines.push("");

  if (exposedEnv.length > 0 || sortedSecrets.some((s) => s.severity === "critical" || s.severity === "high")) {
    lines.push("## Recommended Actions");
    lines.push("");
    if (exposedEnv.length > 0) {
      lines.push("- Add the exposed `.env` file(s) above to `.gitignore` immediately.");
    }
    lines.push("- Rotate/revoke any credentials listed above that may have already been committed or shared.");
    lines.push("- Re-scan after remediation to confirm all issues are resolved.");
    lines.push("");
  }

  lines.push("---");
  lines.push("_Generated by Security Token Janitor_");
  lines.push("");

  return lines.join("\n");
}

export function downloadMarkdownReport(scan) {
  const markdown = buildMarkdownReport(scan);
  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "security-report.md";
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
